services:
  app_blue:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app_blue
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
    ports:
      - "8000:8000"