version: "3.8"

services:
  app_blue:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app_blue
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - PYTHONUNBUFFERED=1
      - APP_VERSION=blue
    volumes:
      - ../app:/app
    ports:
      - "8001:8000"

  app_green:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app_green
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - PYTHONUNBUFFERED=1
      - APP_VERSION=green
    volumes:
      - ../app:/app
    ports:
      - "8002:8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/upstream.conf.template:/etc/nginx/upstream.conf.template:ro
      - ./nginx/promote.sh:/usr/local/bin/promote.sh
      - nginx_conf:/etc/nginx/conf.d
    entrypoint: /bin/sh -c "sed 's/__TARGET__/app_blue/' /etc/nginx/upstream.conf.template > /etc/nginx/conf.d/upstream.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - app_blue
      - app_green

volumes:
  nginx_conf: